import type { TestBuild } from "./audit-lib.js";

/** Diverse builds covering all 9 classes, subclasses, roles, backgrounds, additional powers. */
export const TEST_BUILDS: TestBuild[] = [
  {
    id: "fighter-champion-captain",
    label: "Fighter / Champion / Captain",
    classIdentifier: "fighter",
    subclassIdentifier: "champion",
    roleSlug: "captain",
    style: "player",
  },
  {
    id: "rogue-assassin-archaeologist-navigator",
    label: "Rogue / Assassin / Archaeologist / Navigator",
    classIdentifier: "rogue",
    subclassIdentifier: "assassin",
    backgroundSlug: "Archaeologist",
    roleSlug: "navigator",
    style: "player",
  },
  {
    id: "barbarian-berserker-helmsman",
    label: "Barbarian / Berserker / Helmsman",
    classIdentifier: "barbarian",
    subclassIdentifier: "berserker",
    roleSlug: "helmsman",
    style: "player",
  },
  {
    id: "bard-lore-author-cook",
    label: "Bard / Lore / Author / Cook",
    classIdentifier: "bard",
    subclassIdentifier: "lore",
    backgroundSlug: "Author",
    roleSlug: "cook",
    style: "player",
  },
  {
    id: "brawler-open-hand-acrobat",
    label: "Brawler / Open Hand / Acrobat",
    classIdentifier: "brawler",
    subclassIdentifier: "open-hand",
    backgroundSlug: "Acrobat",
    style: "player",
  },
  {
    id: "marksman-sniper-master-at-arms",
    label: "Marksman / Sniper / Master at Arms",
    classIdentifier: "marksman",
    subclassIdentifier: "sniper",
    roleSlug: "master-at-arms",
    style: "player",
  },
  {
    id: "gadgeteer-alchemist-scholar",
    label: "Gadgeteer / Alchemist / Scholar",
    classIdentifier: "gadgeteer",
    subclassIdentifier: "alchemist",
    roleSlug: "scholar",
    style: "player",
  },
  {
    id: "medic-bio-engineer-mutant",
    label: "Medic / Bio-Engineer / Mutant Metamorphosis",
    classIdentifier: "medic",
    subclassIdentifier: "bio-engineer",
    backgroundSlug: "Doctor",
    additionalPowerSlug: "mutant-metamorphosis",
    style: "player",
  },
  {
    id: "savant-burning-six-powers",
    label: "Savant / Burning Passion / Six Powers Adept",
    classIdentifier: "savant",
    subclassIdentifier: "burning-passion",
    additionalPowerSlug: "six-powers-adept",
    style: "player",
  },
  {
    id: "npc-fighter-champion-minimal",
    label: "NPC-style Fighter / Champion (no bg/role/power)",
    classIdentifier: "fighter",
    subclassIdentifier: "champion",
    style: "npc",
  },
  {
    id: "medic-field-surgeon-shipwright",
    label: "Medic / Field Surgeon / Shipwright",
    classIdentifier: "medic",
    subclassIdentifier: "field-surgeon",
    roleSlug: "shipwright",
    style: "player",
  },
];
