// The automated ship-check stages, in order: [name, command, what it checks]. One list for the runner and the status page.
export const STAGES = [
  ["build", "npm run build", "Building the compendium packs"],
  ["validate+regression+unit", "node scripts/validate-packs.mjs && node scripts/regression.mjs && npm test", "Pack validation, nothing from the old baseline regressed, unit tests"],
  ["images", "node scripts/check-images.mjs", "Every image resolves"],
  ["source checks", "node scripts/check-armor.mjs && node scripts/check-class-tables.mjs && node scripts/check-items-vs-source.mjs && node scripts/check-races-vs-source.mjs && node scripts/check-automation-accuracy.mjs", "Armor, classes, items, races against the sourcebook"],
  ["sync to live world", "node dev/harness/sync-live.mjs --force", "Pushing the build into the running test world"],
  ["prerequisites", "node dev/harness/prereq.mjs", "Feat prerequisite cases"],
  ["wizard", "node dev/harness/wizard.mjs", "Create OPC wizard cases"],
  ["level-up", "node dev/harness/levelup.mjs", "Every class and subclass, level 1 to 20"],
  ["optional rules", "node dev/harness/optional-rules.mjs", "Optional rule toggles"],
  ["sweep", "node dev/harness/sweep-parallel.mjs", "Using every compendium document once"],
  ["rebuild PCs", "node dev/harness/rebuild-pcs.mjs", "Rebuilding the 10 campaign PCs"],
  ["transformations", "node dev/harness/transform.mjs", "Zoan Hybrid/Full Beast and Sulong on the PCs"],
  ["rules", "node dev/harness/rules.mjs", "Devil Fruit Uses, Haki tiers and the Brawler die by level"],
  ["batch 1 features", "node dev/harness/batch1.mjs", "Batch 1 text-only features change the numbers their text promises"],
  ["batch 4 features", "node dev/harness/text-batch4.mjs", "The 17 text-only features approved as usable: cocktails, drunkard, afterimage, passives"],
  ["batch 5 features", "node dev/harness/text-batch5.mjs", "Conditional features as toggles and buttons: toggles start off and change the right number"],
  ["batch 6 features", "node dev/harness/text-batch6.mjs", "Second group of conditional features: toggles, buttons, Ordnance Requiem dice, die steps"],
  ["animations", "node dev/harness/animations.mjs", "OP5e autorec entries merged into Automated Animations with valid ids; AA loads clean"],
  ["shop and trade", "node dev/harness/shop-trade.mjs", "Standalone shop module: buy, sell, trade, funds, stock, permissions"],
  ["shop approval", "node dev/harness/shop-approval.mjs", "GM and two players: show, presence, cart, approve, decline, cancel, permissions"],
  ["fruit casting", "node dev/harness/fruit-casting.mjs", "Devil Fruit Uses as spell points; Zoans cast only in a form"],
  ["summons and ships", "node dev/harness/summons-ships.mjs", "Summon profiles resolve; cannons attack and have range; ships have HP, AC and linked cannons"],
  ["multi-player", "node dev/harness/multiplayer.mjs", "GM plus two players at once: permissions, whispers, shared combat, effects"],
  ["real-UI walkthroughs", "node dev/harness/walkthrough-all.mjs", "Sheets, dialogs, summons, ships and item galleries in a real browser"],
];
