// The automated ship-check stages, in order: [name, command, what it checks]. One list for the runner and the status page.
export const STAGES = [
  ["build", "npm run build", "Building the compendium packs"],
  ["validate+regression+unit", "node scripts/validate-packs.mjs && node scripts/regression.mjs && npm test", "Pack validation, nothing from the old baseline regressed, unit tests"],
  ["images", "node scripts/check-images.mjs", "Every image resolves"],
  ["source checks", "node scripts/check-armor.mjs && node scripts/check-class-tables.mjs && node scripts/check-items-vs-source.mjs && node scripts/check-races-vs-source.mjs && node scripts/check-automation-accuracy.mjs", "Armor, classes, items, races against the sourcebook"],
  ["sync to live world", "node dev/harness/sync-live.mjs --force", "Pushing the build into the running test world"],
  ["prerequisites", "node dev/harness/prereq.mjs", "Feat prerequisite cases"],
  ["wizard", "node dev/harness/wizard.mjs", "Create OPC wizard cases"],
  ["level-up", "node dev/harness/levelup.mjs", "Every class and subclass, level 1 to 20"],
  ["optional rules", "node dev/harness/optional-rules.mjs", "Optional rule toggles"],
  ["sweep", "node dev/harness/sweep-parallel.mjs", "Using every compendium document once"],
  ["rebuild PCs", "node dev/harness/rebuild-pcs.mjs", "Rebuilding the 10 campaign PCs"],
  ["transformations", "node dev/harness/transform.mjs", "Zoan Hybrid/Full Beast and Sulong on the PCs"],
  ["rules", "node dev/harness/rules.mjs", "Devil Fruit Uses, Haki tiers and the Brawler die by level"],
  ["batch 1 features", "node dev/harness/batch1.mjs", "Batch 1 text-only features change the numbers their text promises"],
  ["batch 4 features", "node dev/harness/text-batch4.mjs", "The 17 text-only features approved as usable: cocktails, drunkard, afterimage, passives"],
  ["batch 5 features", "node dev/harness/text-batch5.mjs", "Conditional features as toggles and buttons: toggles start off and change the right number"],
  ["batch 6 features", "node dev/harness/text-batch6.mjs", "Second group of conditional features: toggles, buttons, Ordnance Requiem dice, die steps"],
  ["batch 7 features", "node dev/harness/text-batch7.mjs", "Last group: stances, totems, auras, Achilles Heel, Legendary Flourish, Signature Fighting Style"],
  ["old characters", "node dev/harness/import-old.mjs", "The nine old campaign sheets rebuild through Create OPC and carry their gear, proficiencies and berries"],
  ["animations", "node dev/harness/animations.mjs", "OP5e autorec entries merged into Automated Animations with valid ids; AA loads clean"],
  ["shop and trade", "node dev/harness/shop-trade.mjs", "Standalone shop module: buy, sell, trade, funds, stock, permissions"],
  ["shop approval", "node dev/harness/shop-approval.mjs", "GM and two players: show, presence, cart, approve, decline, cancel, permissions"],
  ["shop coins", "node dev/harness/shop-coins.mjs", "Shop money with stock dnd5e coins and change making (stand-in actor)"],
  ["fruit casting", "node dev/harness/fruit-casting.mjs", "Devil Fruit Uses as spell points; Zoans cast only in a form"],
  ["token auras", "node dev/harness/auras.mjs", "Aura of Freedom/Courage/Devotion/Tenacity become Aura Effects auras on a character"],
  ["turn expiry", "node dev/harness/turn-expiry.mjs", "An effect with a turn-start special duration ends exactly at the source's next turn"],
  ["token-effect items", "node dev/harness/atl-items.mjs", "Torch, candle, lantern, night-vision goggles switch the token light and sight through ATL"],
  ["effects pack", "node dev/harness/effects-pack.mjs", "Premade effects: Dodge, Help, Half and Three-Quarters Cover"],
  ["canvas effects", "node dev/harness/canvas-fx.mjs", "Big-hit screen shake and burst: triggers, threshold, per-player opt-out"],
  ["extra sources", "node dev/harness/extra-sources.mjs", "An extra item compendium adds its feats (with source) to the free feat; the character gets it"],
  ["performance", "node dev/harness/perf.mjs", "op5e cost budget: script load, item creation, actor updates, startup sweeps"],
  ["falling", "node dev/harness/falling.mjs", "Falling damage: 3d6 for 35 ft, applied with prone; 5 ft does nothing"],
  ["summons and ships", "node dev/harness/summons-ships.mjs", "Summon profiles resolve; cannons attack and have range; ships have HP, AC and linked cannons"],
  ["ship cannon", "node dev/harness/ships-fire.mjs", "A ship actor opens in the real UI and its cannon fires"],
  ["multi-player", "node dev/harness/multiplayer.mjs", "GM plus two players at once: permissions, whispers, shared combat, effects"],
  ["real-UI walkthroughs", "node dev/harness/walkthrough-all.mjs", "Sheets, dialogs, summons, ships and item galleries in a real browser"],
];
